#!/bin/sh
/usr/local/bin/python2 main.py \
    -u http://www.cs.ccu.edu.tw/ \
    -d '[^/]*.cs.ccu.edu.tw' \
    -t 10 \
    -T 2 \
    -l 128 \
    -F drupal \
    -f iso \
    -f flv \
    -f avi \
    -f exe \
    -f wav \
    -f pdf \
    #-f mp3 \
    #-f 7z \
    #-f rar \
    #-f tgz \
    #-f tar.gz \
    #-f zip \
    #-f docx \
    #-f doc \
    #-f xls \
    #-f xlsx \
    #-f pptx \
    #-f ppt \
    #-f pdf \
    #-f JPG \
    #-f jpg \
    #-f png \
    #-f css \
    #-f js \
    #-f gif \
    #-f ico \
    #-f bmp \
    #-w res \
